# Generated by Django 5.1.6 on 2025-03-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status_applicationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('cancelled', 'Cancelled')], default='delivered', max_length=20),
        ),
    ]
