# Generated by Django 5.1.6 on 2025-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.JSONField(default=list),
        ),
    ]
