# Generated by Django 5.1.6 on 2025-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('skills', models.JSONField()),
                ('experience', models.JSONField()),
                ('education', models.JSONField()),
                ('tfidf_score', models.FloatField()),
                ('semantic_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
