# Generated by Django 5.1.6 on 2025-02-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_created_77460a_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_is_acti_b6ae73_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.employerprofile'),
        ),
    ]
